"""
Render an AuditPackage to a professional PDF with reportlab.

Kept separate from assembly (audit_service) so the data and its presentation stay
independent. The layout favours an auditor's clarity over decoration: a header and
footer on every page (plant name, timestamp, page numbers), and tables whose long
cells wrap instead of overflowing.
"""

from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.services.audit_service import AuditPackage

_STYLES = getSampleStyleSheet()
_CELL = ParagraphStyle("cell", parent=_STYLES["BodyText"], fontSize=8, leading=10)
_CELL_BOLD = ParagraphStyle("cellb", parent=_CELL, fontName="Helvetica-Bold")
_H2 = ParagraphStyle("h2", parent=_STYLES["Heading2"], fontSize=12, spaceBefore=10, spaceAfter=4, textColor=colors.HexColor("#1e3a5f"))

_STATUS_COLOR = {
    "compliant": colors.HexColor("#2e7d32"),
    "due_soon": colors.HexColor("#b26a00"),
    "overdue": colors.HexColor("#c62828"),
    "missing_evidence": colors.HexColor("#c62828"),
}
_USABLE_WIDTH = A4[0] - 30 * mm


def render_audit_pdf(package: AuditPackage) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm, topMargin=22 * mm, bottomMargin=18 * mm,
        title=f"Compliance Audit Package - {package.cover.scope}",
    )

    story = []
    story += _cover(package)
    story += _summary(package)
    story += _equipment_section(package)
    story += _compliance_section(package)
    story += _incidents_section(package)
    story += _permits_section(package)
    story += _maintenance_section(package)
    story += _predictions_section(package)

    doc.build(story, onFirstPage=_page_furniture(package), onLaterPages=_page_furniture(package))
    return buffer.getvalue()


# --- page header/footer ---

def _page_furniture(package: AuditPackage):
    plant = package.cover.plant_name

    def draw(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#666666"))
        canvas.drawString(15 * mm, A4[1] - 12 * mm, f"{plant} - HSE Compliance Audit Package")
        canvas.drawRightString(A4[0] - 15 * mm, A4[1] - 12 * mm, package.cover.generated_at)
        canvas.line(15 * mm, A4[1] - 14 * mm, A4[0] - 15 * mm, A4[1] - 14 * mm)
        canvas.drawString(15 * mm, 10 * mm, "Generated by SANJEEVANI - traceable to source records")
        canvas.drawRightString(A4[0] - 15 * mm, 10 * mm, f"Page {doc.page}")
        canvas.restoreState()

    return draw


# --- sections ---

def _cover(p: AuditPackage) -> list:
    return [
        Paragraph("HSE Compliance Audit Package", _STYLES["Title"]),
        Paragraph(f"{p.cover.plant_name}", _STYLES["Heading3"]),
        Spacer(1, 4),
        Paragraph(f"Scope: {p.cover.scope}", _CELL),
        Paragraph(f"Generated: {p.cover.generated_at}", _CELL),
        Paragraph(f"Compliance reference date: {p.cover.reference_date}", _CELL),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1e3a5f"), spaceBefore=6, spaceAfter=6),
    ]


def _summary(p: AuditPackage) -> list:
    s = p.summary
    line = (
        f"Compliant: {s.get('compliant', 0)}   Due soon: {s.get('due_soon', 0)}   "
        f"Overdue: {s.get('overdue', 0)}   No record: {s.get('missing_evidence', 0)}   |   "
        f"Permits: {s.get('permits', 0)}   Acknowledged interventions: {s.get('acknowledged_interventions', 0)}   "
        f"Open/overdue maintenance: {s.get('open_or_overdue_maintenance', 0)}"
    )
    return [Paragraph("Summary", _H2), Paragraph(line, _CELL), Spacer(1, 4)]


def _equipment_section(p: AuditPackage) -> list:
    header = ["Tag", "Name", "Work orders", "Incidents"]
    rows = [[Paragraph(e.tag, _CELL_BOLD), Paragraph(e.name or "", _CELL), str(e.work_orders), str(e.incidents)] for e in p.equipment]
    return [Paragraph("Equipment register", _H2), _table([header] + rows, [25 * mm, 95 * mm, 30 * mm, 30 * mm])]


def _compliance_section(p: AuditPackage) -> list:
    header = ["Status", "H/S/E", "Requirement", "Regulation", "Evidence / gap"]
    rows = []
    for f in p.compliance:
        evidence = f"{f.evidence_ref} ({f.evidence_date})" if f.evidence_ref and f.evidence_date else (f.gap or f.evidence_ref or "-")
        rows.append([
            _status_para(f.status),
            Paragraph(f.category, _CELL),
            Paragraph(f.title, _CELL),
            Paragraph(f.regulation, _CELL),
            Paragraph(evidence, _CELL),
        ])
    return [Paragraph("Compliance findings", _H2), _table([header] + rows, [22 * mm, 18 * mm, 50 * mm, 45 * mm, 45 * mm])]


def _incidents_section(p: AuditPackage) -> list:
    if not p.incidents:
        return []
    header = ["Incident", "Equipment", "Date", "Description"]
    rows = [[Paragraph(i.id, _CELL_BOLD), Paragraph(i.equipment_tag, _CELL), Paragraph(i.date or "", _CELL), Paragraph(i.description or "", _CELL)] for i in p.incidents]
    return [Paragraph("Incident history", _H2), _table([header] + rows, [28 * mm, 24 * mm, 22 * mm, 106 * mm])]


def _permits_section(p: AuditPackage) -> list:
    out = [Paragraph("Permits and acknowledged safety interventions", _H2)]
    if not p.permits:
        out.append(Paragraph("No permits raised in this scope.", _CELL))
        return out

    for permit in p.permits:
        out.append(Paragraph(
            f"{permit.permit_id} - {permit.permit_type} on {permit.equipment_tag} - raised by {permit.created_by or 'unknown'} ({permit.created_date})",
            _CELL_BOLD,
        ))
        if permit.acknowledged:
            header = ["Acknowledged intervention", "Severity", "Cited"]
            rows = [[Paragraph(a.title, _CELL), Paragraph(a.severity, _CELL), Paragraph(a.cited or "", _CELL)] for a in permit.acknowledged]
            out.append(_table([header] + rows, [110 * mm, 25 * mm, 45 * mm]))
        else:
            out.append(Paragraph("No interventions were required.", _CELL))
        out.append(Spacer(1, 4))
    return out


def _maintenance_section(p: AuditPackage) -> list:
    if not p.maintenance:
        return []
    header = ["Work order", "Equipment", "Date", "Status", "Note"]
    rows = [[Paragraph(m.wo_id, _CELL_BOLD), Paragraph(m.equipment_tag, _CELL), Paragraph(m.date or "", _CELL), Paragraph(m.status or "", _CELL), Paragraph(m.note, _CELL)] for m in p.maintenance]
    return [Paragraph("Maintenance evidence", _H2), _table([header] + rows, [28 * mm, 24 * mm, 24 * mm, 24 * mm, 80 * mm])]


def _predictions_section(p: AuditPackage) -> list:
    if not p.predictions:
        return []
    header = ["Equipment", "Predicted failure", "Risk", "Confidence", "Projected", "Evidence"]
    rows = [[
        Paragraph(pr.equipment_tag, _CELL_BOLD), Paragraph(pr.failure_label, _CELL), Paragraph(pr.risk_level or "", _CELL),
        Paragraph(f"{pr.confidence}%" if pr.confidence is not None else "", _CELL), Paragraph(pr.predicted_center or "", _CELL),
        Paragraph(", ".join(pr.evidence), _CELL),
    ] for pr in p.predictions]
    return [Paragraph("Predictive findings (forward-looking risk)", _H2), _table([header] + rows, [22 * mm, 40 * mm, 20 * mm, 22 * mm, 26 * mm, 50 * mm])]


# --- helpers ---

def _status_para(status: str) -> Paragraph:
    style = ParagraphStyle("st", parent=_CELL_BOLD, textColor=_STATUS_COLOR.get(status, colors.black))
    label = {"compliant": "Compliant", "due_soon": "Due soon", "overdue": "Overdue", "missing_evidence": "No record"}.get(status, status)
    return Paragraph(label, style)


def _table(data: list, col_widths: list) -> Table:
    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f6f8")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return table
